#!/bin/bash
# Fetch latest reports from Colab to analyze issues

echo "🔍 Fetching latest meeting reports from Colab..."
echo ""
echo "Please run these commands in your Colab notebook to export the reports:"
echo ""
echo "------- COPY AND RUN IN COLAB -------"
echo ""
echo "# 1. Show latest meeting summary"
echo "!cat /content/multi-agent/reports/summary_20251014_025937.md"
echo ""
echo "# 2. Show latest actions"
echo "!cat /content/multi-agent/reports/actions_20251014_025937.json"
echo ""
echo "# 3. Show latest transcript (last 100 lines)"
echo "!tail -100 /content/multi-agent/reports/transcript_20251014_025937.md"
echo ""
echo "# 4. Check handoff actions"
echo "!cat /content/multi-agent/reports/handoff/pending_actions.json"
echo ""
echo "# 5. Check executive log for errors"
echo "!tail -50 /content/multi-agent/reports/executive.log"
echo ""
echo "------- END COLAB COMMANDS -------"
echo ""
echo "Copy the output and save to:"
echo "  - summary -> /Users/guyan/computer_vision/computer-vision/multi-agent/latest_summary.md"
echo "  - actions -> /Users/guyan/computer_vision/computer-vision/multi-agent/latest_actions.json"
echo "  - transcript -> /Users/guyan/computer_vision/computer-vision/multi-agent/latest_transcript.md"
echo "  - handoff -> /Users/guyan/computer_vision/computer-vision/multi-agent/latest_handoff.json"
echo "  - exec log -> /Users/guyan/computer_vision/computer-vision/multi-agent/latest_exec.log"
echo ""
echo "Then I can analyze what went wrong."
