# Consolidated Multi-Agent Coordination System (5 Agents)
# Version: 3.0
# Purpose: Streamlined autonomous execution with 14→5 agent consolidation
# Agents: Planning Team (4) + Executive Team (3)... with 1 shared agent (Ops Commander reports to Strategic Leader)

metadata:
  created: "2025-10-14"
  version: "3.0"
  consolidation: "14_agents → 5_agents"
  purpose: "Autonomous V1.0 Deployment + CVPR 2025 Research Coordination"
  cost_optimization: "67% reduction in API costs"
  meeting_speed: "55% faster (30 min vs. 66 min)"
  google_colab_integration: enabled
  smoke_testing: enabled
  file_editing: enabled

# =============================================================================
# CONSOLIDATED HIERARCHY (5 AGENTS)
# =============================================================================

hierarchy:

  # =========================================================================
  # PLANNING TEAM (4 agents) - Strategic Decision Making
  # =========================================================================
  planning_team:

    - role: "Strategic Leader"
      agent_id: "strategic_leader"
      model: "claude-opus-4-20250514"
      authority: "STRATEGIC_DECISION"
      reports_to: null  # Top of Planning Team
      manages: ["empirical_validation_lead", "critical_evaluator", "gemini_advisor"]

      consolidated_from:
        - "Planning Moderator"
        - "Pre-Architect"
        - "Research Director"
        - "CoTRR Team"

      responsibilities:
        - "Meeting moderation & synthesis"
        - "System architecture design"
        - "CVPR 2025 paper coordination"
        - "CoTRR optimization & lightweight variant development"
        - "Final decision matrix (GO/PAUSE_AND_FIX/REJECT)"
        - "Handoff to Executive Team"

      file_editing: true
      prompt_file: "multi-agent/agents/prompts/planning_team/01_strategic_leader.md"

    - role: "Empirical Validation Lead"
      agent_id: "empirical_validation_lead"
      model: "claude-sonnet-4-20250514"
      reports_to: "strategic_leader"

      consolidated_from:
        - "Data Analyst"
        - "Tech Analysis Team"

      responsibilities:
        - "Data integrity & metrics verification"
        - "Statistical validation (CI95, p-values, effect sizes)"
        - "Quantitative evaluation & ROI scoring"
        - "Reproducibility validation"
        - "Artifact scanning & progress updates"

      file_editing: true
      prompt_file: "multi-agent/agents/prompts/planning_team/02_empirical_validation_lead.md"

    - role: "Critical Evaluator & Integrity Guardian"
      agent_id: "critical_evaluator"
      model: "gpt-4-turbo"
      reports_to: "strategic_leader"

      consolidated_from:
        - "OpenAI Critic"
        - "Integrity Guardian"

      responsibilities:
        - "Adversarial validation & scientific auditing"
        - "Provenance verification & compliance certification"
        - "Data integrity & artifact chain validation"
        - "Integrity Score (0-100) assignment"
        - "Risk escalation (PAUSE_AND_FIX if integrity < threshold)"

      file_editing: false  # Advisory only
      prompt_file: "multi-agent/agents/prompts/planning_team/03_critical_evaluator_openai.md"

    - role: "Gemini Research Advisor"
      agent_id: "gemini_advisor"
      model: "gemini-2.0-flash-exp"
      reports_to: "strategic_leader"

      consolidated_from:
        - "Gemini Feasibility Search (unchanged)"

      responsibilities:
        - "Literature review & research breadth expansion"
        - "Architecture scouting & precedent mapping"
        - "Feasibility analysis & innovation discovery"
        - "CVPR 2025 related work analysis"

      file_editing: false  # Read-only for external research
      prompt_file: "multi-agent/agents/prompts/planning_team/04_gemini_research_advisor.md"

  # =========================================================================
  # EXECUTIVE TEAM (3 agents) - Tactical Execution
  # =========================================================================
  executive_team:

    - role: "Ops Commander"
      agent_id: "ops_commander"
      model: "claude-sonnet-4-20250514"  # Changed from Opus 4 to Sonnet 4 for cost optimization
      authority: "EXECUTION_DECISION"
      reports_to: "strategic_leader"  # Reports to Planning Team Strategic Leader
      manages: ["quality_safety_officer", "infrastructure_performance_monitor"]

      consolidated_from:
        - "Original Ops Commander"
        - "Integration Engineer (duties added)"

      responsibilities:
        - "Execute Planning Team directives (NOT strategic decisions)"
        - "Run experiments & deployments as instructed"
        - "Integration validation (schema, dependencies)"
        - "Report results back to Planning Team via execution_progress_update.md"
        - "Coordinate with Executive Team for execution meetings"

      chain_of_command: "Planning Team decides → Executive Team executes"

      file_editing: true
      prompt_file: "multi-agent/agents/prompts/executive_team/02_ops_commander.md"

    - role: "Quality & Safety Officer"
      agent_id: "quality_safety_officer"
      model: "gpt-4-turbo"
      reports_to: "ops_commander"

      consolidated_from:
        - "Compliance Monitor"
        - "Latency Analyst"
        - "Rollback Officer"

      responsibilities:
        - "Compliance validation (metrics, drift, calibration)"
        - "Performance profiling & latency analysis"
        - "SLO monitoring (all 6 SLOs)"
        - "Rollback management (RTO ≤ 10 min, RPO ≤ 5 min)"
        - "Emergency rollback triggers"

      file_editing: false  # Monitoring only
      prompt_file: "multi-agent/agents/prompts/executive_team/01_quality_safety_officer.md"

    - role: "Infrastructure & Performance Monitor"
      agent_id: "infrastructure_performance_monitor"
      model: "claude-sonnet-4-20250514"
      reports_to: "ops_commander"

      consolidated_from:
        - "Infra Guardian"
        - "Enhanced performance monitoring"

      responsibilities:
        - "Environment stability & reproducibility"
        - "Performance profiling & latency analysis"
        - "Resource monitoring (CPU, GPU, memory)"
        - "Capacity planning & baseline verification"
        - "Container integrity & dependency management"

      file_editing: false  # Monitoring only
      prompt_file: "multi-agent/agents/prompts/executive_team/03_infrastructure_performance_monitor.md"

# =============================================================================
# HANDOFF MECHANISM (Planning → Executive)
# =============================================================================

handoff:

  # Planning Team outputs for Executive Team
  planning_outputs:
    - file: "multi-agent/handoff/pending_actions.json"
      format: "structured_json"
      schema:
        decisions: "array"  # Each decision has: priority (HIGH/MEDIUM/LOW), action, owner, deadline
        acceptance_gates: "object"
        evidence_paths: "array"
        timestamp: "ISO8601"

    - file: "multi-agent/handoff/decision_matrix.md"
      format: "markdown"
      content: "Strategic Leader's final decision with rationale"

    - file: "multi-agent/handoff/experiment_requests.json"
      format: "structured_json"
      content: "Specific experiments requested by Planning Team"

  # Executive Team outputs for Planning Team
  executive_outputs:
    - file: "multi-agent/handoff/execution_progress_update.md"
      format: "markdown"
      content: "Ops Commander's execution report with results"

    - file: "multi-agent/handoff/experiment_results.json"
      format: "structured_json"
      content: "Results from experiments run by Executive Team"

    - file: "multi-agent/handoff/metrics_report.json"
      format: "structured_json"
      content: "Production metrics, SLO status, deployment state"

# =============================================================================
# SHARED MEMORY & CHANNELS (Simplified for 5 agents)
# =============================================================================

shared_memory:

  state_store:
    type: "json_files"
    location: "multi-agent/state/"
    persistence: "file_system"
    sync_interval_seconds: 60

    stores:
      - name: "deployment_state"
        file: "deployment_state.json"

      - name: "metrics_state"
        file: "metrics_state.json"

      - name: "artifact_registry"
        file: "artifact_registry.json"

      - name: "decision_log"
        file: "decision_log.json"

  channels:

    # Planning Team internal
    - name: "planning_internal"
      subscribers: ["strategic_leader", "empirical_validation_lead", "critical_evaluator", "gemini_advisor"]
      purpose: "Planning Team meeting discussions"

    # Executive Team internal
    - name: "executive_internal"
      subscribers: ["ops_commander", "quality_safety_officer", "infrastructure_performance_monitor"]
      purpose: "Executive Team coordination"

    # Cross-team handoff
    - name: "planning_to_executive"
      publisher: "strategic_leader"
      subscribers: ["ops_commander"]
      purpose: "Strategic decisions → Tactical execution"

    - name: "executive_to_planning"
      publisher: "ops_commander"
      subscribers: ["strategic_leader"]
      purpose: "Execution results → Strategic review"

# =============================================================================
# MEETINGS (Planning Team & Executive Team)
# =============================================================================

meetings:

  # Planning Team meetings (4 agents)
  planning_meeting:
    frequency: "weekly_or_triggered"
    participants: ["strategic_leader", "empirical_validation_lead", "critical_evaluator", "gemini_advisor"]
    duration_minutes: 30  # 55% faster than 14-agent meetings (66 min)
    moderator: "strategic_leader"

    agenda:
      - "Context assimilation & objectives (5 min)"
      - "Evidence weighting & system design (10 min)"
      - "Decision matrix & evaluation plan (10 min)"
      - "Final decision (GO/PAUSE_AND_FIX/REJECT) (5 min)"

    outputs:
      - "multi-agent/handoff/pending_actions.json"
      - "multi-agent/handoff/decision_matrix.md"
      - "multi-agent/reports/planning_meeting_{timestamp}.md"

  # Executive Team meetings (3 agents)
  execution_meeting:
    frequency: "as_needed_for_execution"
    participants: ["ops_commander", "quality_safety_officer", "infrastructure_performance_monitor"]
    duration_minutes: 20
    moderator: "ops_commander"

    agenda:
      - "Read pending_actions.json from Planning Team (3 min)"
      - "Coordinate execution tasks (10 min)"
      - "Report progress and results (7 min)"

    outputs:
      - "multi-agent/handoff/execution_progress_update.md"
      - "multi-agent/handoff/experiment_results.json"
      - "multi-agent/reports/execution_meeting_{timestamp}.md"

# =============================================================================
# TRIGGERS (Simplified for 5 agents)
# =============================================================================

triggers:

  event_triggers:

    # Emergency rollback
    - name: "emergency_rollback"
      event: "slo_breach"
      condition: "compliance_drop > 2pts OR latency_spike > 10% OR error_rate > 1%"
      action:
        type: "initiate_rollback"
        handler: "quality_safety_officer"
        notify: ["ops_commander", "strategic_leader"]
        priority: "CRITICAL"

    # Stage progression
    - name: "stage_progression"
      event: "stage_slo_met"
      condition: "all_slos_pass AND stage_duration >= minimum_time"
      action:
        type: "progress_stage"
        handler: "ops_commander"
        notify: ["strategic_leader"]
        priority: "HIGH"

    # Planning meeting trigger
    - name: "planning_meeting_trigger"
      event: "checkpoint_reached OR significant_progress"
      condition: "new_artifacts > 10 OR days_since_meeting > 7 OR execution_report_received"
      action:
        type: "convene_planning_meeting"
        handler: "strategic_leader"
        participants: ["strategic_leader", "empirical_validation_lead", "critical_evaluator", "gemini_advisor"]

# =============================================================================
# FILE PERMISSIONS (Updated for 5 agents)
# =============================================================================

file_permissions:

  planning_team_edit:
    agents: ["strategic_leader", "empirical_validation_lead"]
    allowed_paths:
      - "docs/**/*.md"
      - "research/plans/**/*.json"
      - "research/analysis/**/*.md"
      - "multi-agent/reports/planning_*.md"
      - "multi-agent/decisions/**/*.json"
      - "multi-agent/handoff/pending_actions.json"
      - "multi-agent/handoff/decision_matrix.md"
    allowed_operations: ["create", "edit", "delete"]
    require_approval: false
    git_commit: true

  executive_team_edit:
    agents: ["ops_commander"]
    allowed_paths:
      - "deploy/**/*.md"
      - "ops/**/*.yaml"
      - "multi-agent/reports/execution_*.md"
      - "multi-agent/state/**/*.json"
      - "multi-agent/handoff/execution_progress_update.md"
      - "multi-agent/handoff/experiment_results.json"
    allowed_operations: ["create", "edit"]
    require_approval: false
    git_commit: true

  advisor_read_only:
    agents: ["critical_evaluator", "gemini_advisor", "quality_safety_officer", "infrastructure_performance_monitor"]
    allowed_paths: ["**/*"]
    allowed_operations: ["read"]
    git_commit: false

# =============================================================================
# HEARTBEAT SYSTEM (Simplified)
# =============================================================================

heartbeat:

  main_cycle:
    interval_minutes: 60
    enabled: true

    phases:
      - phase: "monitoring"
        duration_minutes: 15
        responsible: ["quality_safety_officer", "infrastructure_performance_monitor"]
        parallel: true

      - phase: "decision"
        duration_minutes: 10
        responsible: "ops_commander"

      - phase: "execution"
        duration_minutes: 10
        responsible: "ops_commander"

      - phase: "reporting"
        duration_minutes: 5
        responsible: "ops_commander"
        output_to: "executive_to_planning"

  daily_sync:
    interval_hours: 24
    time_utc: "09:00"
    enabled: true

    actions:
      - type: "artifact_scan"
        agent: "empirical_validation_lead"
      - type: "progress_report"
        agent: "ops_commander"
      - type: "strategic_review"
        agent: "strategic_leader"

  weekly_checkpoint:
    interval_days: 7
    day_of_week: "Monday"
    time_utc: "10:00"
    enabled: true

    actions:
      - type: "convene_planning_meeting"
        handler: "strategic_leader"
      - type: "review_deployment_progress"
        handler: "ops_commander"

# =============================================================================
# SMOKE TESTING (Unchanged)
# =============================================================================

smoke_testing:
  enabled: true
  run_during_meetings: true

  test_suites:
    - name: "sanity_check"
      duration_seconds: 30
      responsible: "ops_commander"

    - name: "performance_smoke"
      duration_seconds: 60
      responsible: "infrastructure_performance_monitor"

    - name: "compliance_smoke"
      duration_seconds: 60
      responsible: "quality_safety_officer"

# =============================================================================
# GOOGLE COLAB INTEGRATION (Unchanged)
# =============================================================================

colab_integration:
  enabled: true
  purpose: "High-performance GPU deployment and testing"

  deployment_workflow:
    - stage: "preparation"
      responsible: "ops_commander"

    - stage: "deployment"
      responsible: "ops_commander"

    - stage: "validation"
      responsible: ["quality_safety_officer", "infrastructure_performance_monitor"]

    - stage: "results"
      responsible: "ops_commander"

  gpu_config:
    preferred_tier: "A100"
    fallback_tiers: ["V100", "T4"]

# =============================================================================
# AUTONOMOUS WORKFLOW (Updated for 5 agents)
# =============================================================================

autonomous_workflow:

  current_mission:
    name: "V1.0_Lightweight_Deployment"
    start_date: "2025-10-14"
    target_completion: "2025-10-21"

    phases:
      - phase: "preparation"
        owner: "ops_commander"
        status: "ready"

      - phase: "shadow_deployment"
        owner: "ops_commander"
        status: "pending"

      - phase: "5_percent_rollout"
        owner: "ops_commander"
        status: "pending"

      - phase: "strategic_review"
        owner: "strategic_leader"
        status: "pending"

  parallel_mission:
    name: "CVPR_2025_Paper"
    owner: "strategic_leader"
    start_date: "2025-10-14"
    abstract_deadline: "2025-11-06"
    paper_deadline: "2025-11-13"

    milestones:
      - "Week 1 (Oct 14-20): Intro + Related Work + protocol"
      - "Week 2 (Oct 21-27): Method + training"
      - "Week 3 (Oct 28-Nov 3): Experiments + Results"
      - "Week 4 (Nov 4-6): Abstract submission"
      - "Week 5 (Nov 7-13): Full paper submission"

# =============================================================================
# ERROR HANDLING (Unchanged)
# =============================================================================

error_handling:
  auto_recovery:
    enabled: true

  escalation:
    levels:
      - level: "P0_critical"
        response_time_minutes: 1
        notify: ["strategic_leader", "ops_commander", "quality_safety_officer"]
        auto_action: "immediate_rollback"

# =============================================================================
# HUMAN OVERSIGHT (Unchanged)
# =============================================================================

human_oversight:
  notification_triggers:
    - "P0_critical_incident"
    - "conflicting_decisions"
    - "deployment_to_50%_or_higher"

  approval_required:
    - "rollback_to_previous_major_version"
    - "architectural_change_proposed"

# =============================================================================
# CONFIGURATION END
# =============================================================================

version: "3.0"
last_updated: "2025-10-14"
status: "ready_for_deployment"
consolidation_summary:
  original_agents: 14
  consolidated_agents: 5
  cost_reduction: "67%"
  meeting_speed_improvement: "55%"
  duty_coverage: "100%"
